// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries-templates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTemplate = `-- name: DeleteTemplate :exec
DELETE FROM templates WHERE templates.id = $1 AND templates.workspace_id IN (
    SELECT id FROM workspaces WHERE owner_id = $2
)
`

type DeleteTemplateParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID string      `json:"owner_id"`
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteTemplate, arg.ID, arg.OwnerID)
	return err
}

const incrementTemplateUses = `-- name: IncrementTemplateUses :one
UPDATE templates SET uses_count = uses_count + 1 WHERE id = $1 RETURNING uses_count
`

func (q *Queries) IncrementTemplateUses(ctx context.Context, id pgtype.UUID) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, incrementTemplateUses, id)
	var uses_count pgtype.Int4
	err := row.Scan(&uses_count)
	return uses_count, err
}

const listUserTemplates = `-- name: ListUserTemplates :many
SELECT t.id, t.name, t.description, t.config, t.is_public, t.workspace_id, t.created_at, t.price_id, t.is_premium, t.author_id, t.uses_count FROM templates t 
WHERE t.workspace_id IN (
    SELECT w.id FROM workspaces w WHERE w.owner_id = $1
) OR t.is_public = true
ORDER BY t.created_at DESC
`

func (q *Queries) ListUserTemplates(ctx context.Context, ownerID string) ([]Template, error) {
	rows, err := q.db.Query(ctx, listUserTemplates, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Config,
			&i.IsPublic,
			&i.WorkspaceID,
			&i.CreatedAt,
			&i.PriceID,
			&i.IsPremium,
			&i.AuthorID,
			&i.UsesCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE templates SET name = COALESCE($1, name), description = COALESCE($2, description), config = COALESCE($3, config), is_public = COALESCE($4, is_public) WHERE templates.id = $5 AND templates.workspace_id IN (
    SELECT id FROM workspaces WHERE owner_id = $6
) RETURNING id, name, description, config, is_public, workspace_id, created_at, price_id, is_premium, author_id, uses_count
`

type UpdateTemplateParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Config      []byte      `json:"config"`
	IsPublic    pgtype.Bool `json:"is_public"`
	ID          pgtype.UUID `json:"id"`
	OwnerID     string      `json:"owner_id"`
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (Template, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.Name,
		arg.Description,
		arg.Config,
		arg.IsPublic,
		arg.ID,
		arg.OwnerID,
	)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Config,
		&i.IsPublic,
		&i.WorkspaceID,
		&i.CreatedAt,
		&i.PriceID,
		&i.IsPremium,
		&i.AuthorID,
		&i.UsesCount,
	)
	return i, err
}
